### ISSUE TITLE
Confusing error

### ISSUE THREAD

**Issue by allisonkarlitskaya** [LibreLingo/LibreLingo-ES-from-EN#17]
I'm not sure how this happened, but here's a screenshot:

![image](https://user-images.githubusercontent.com/36541154/224292990-7c0a7221-9810-452b-86da-b74bf13fe683.png)

**Comment by kantord** [comment]
that seems to be related more so to LibreLingo itself, not really the course. Can you please report it here? https://github.com/LibreLingo/LibreLingo/issues
